### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by poxin13** [Genghis1227/guide_eap_proxy#3]
Are you meant to plug the ATT Router from their 4 port switch side (yellow ports) into the ER? Or from the ONT Port (red port) on the Router into the ER?

Oddly, it seems if I use the 4 ports on the ATT router into the ER, I get the IP in ER gui for eth1 "AT&T Router" but no IP under vlan eth0.0 and my connection does not work

If I use the ONT port on the router into the ER I get an ip on the vlan but not eth1. My connection works here. This also causes the ATT Router to have a blinking red led.

Both configurations above I have the actual ONT going into the ER eth0

**Comment by Genghis1227** [comment]
eth0 = WAN (the connection from the ONT)
eth1 = AT&T Router
eth2 = LAN

So eth0 should be the cable that is from the ONT that use to go to the WAN port of the AT&T router. Now it hooks up to eth0 of the ERL. 

eth1 hooks up to the AT&T router (WAN port, Red port), where you use to hook up the line in from the ONT.

eth2 goes to your LAN, switch or whatever
