### ISSUE TITLE
dhcp client 

### ISSUE THREAD

**Issue by braddux** [Genghis1227/guide_eap_proxy#6]
I use a mesh network wifi device, and this requires being configured as the dhcp server. I'm trying to avoid double-NAT-ing.

Is there a way to configure this so that the EdgeRouter grabs an IP for its LAN interface and passes the WAN IP through?

It seem like it should be possible, but I think I'm missing something.

ONT -> eth0
AT&T router -> eth1
mesh WAN -> eth2 (could drop this, but I think it is needed to pass the WAN IP along).
mesh LAN -> eth3

**Comment by Genghis1227** [comment]
I use the Google WiFi mesh network. No issues in this implemention. Everything comes out as if it were from the WAN IP. The only additional step is you have to configure the ERL to open the port to your router for whatever port, then do the port forwarding in your mesh router as normal.

**Comment by braddux** [comment]
Does your Google WiFi receive the public IP, or an internal 192.168.2.X
IP?  I'm seeing the latter, which means it is double NAT-ed, correct?

Is this what you have?

ONT -> ER eth0
            ER eth1 -> AT&T router
            ER eth2 -> Google WiFi WAN port  -> ...

**Comment by Genghis1227** [comment]
The google wifi does not get the external WAN IP.  The external WAN IP is held by the VLAN and that VLAN is configured to your router.  I don't think it is exactly a double NAT scenario...since the VLAN is masquerading as the WAN.

**Comment by braddux** [comment]
I believe WAN masqurading is the first level of NAT
<https://help.ui.com/hc/en-us/articles/204976494-EdgeRouter-Source-NAT-and-Masquerade>and
then the Google WiFi is doing the second NAT.

Do you believe it should be possible to give the WAN IP to the Google WiFi
and have the VLAN not have it?

- Brad

**Comment by Genghis1227** [comment]
I haven't tried it...give it a shot and let me know.  I can update the guide to provide both options.
