### ISSUE TITLE
Lan on eth3 and eth4?

### ISSUE THREAD

**Issue by joshuarlowry** [Genghis1227/guide_eap_proxy#8]
I'm not sure what I'm missing but I think I need to do extra configuration for dhcp to work on eth 3 and 4. Any tips?

**Comment by joshuarlowry** [comment]
Is it appropriate to shift the configurations for eth2 over to switch0? Is it not that simple?

set interfaces switch switch0 address 192.168.2.254/24
set interfaces switch switch0 description LAN
set interfaces switch switch0 mtu 1500

set port-forward lan-interface switch0

set service dns forwarding listen-on switch0

set interfaces ethernet eth0 vif 0 dhcpv6-pd pd 1 interface switch0 host-address '::1'
set interfaces ethernet eth0 vif 0 dhcpv6-pd pd 1 interface switch0 no-dns
set interfaces ethernet eth0 vif 0 dhcpv6-pd pd 1 interface switch0 prefix-id ':0'
set interfaces ethernet eth0 vif 0 dhcpv6-pd pd 1 interface switch0 service slaac

set service nat rule 6000 outbound-interface switch0

set service upnp2 listen-on switch0

**Comment by saivanap98** [comment]
My setup used different port mappings for the ONT and router, but I manged to get the LAN switch working. I had to change the LAN interface setup and replace eth2 with switch0 everywhere else.

```
set interfaces switch switch0 address 192.168.2.254/24
set interfaces switch switch0 description LAN
set interfaces switch switch0 mtu 1500
set interfaces switch switch0 switch-port interface eth2
set interfaces switch switch0 switch-port interface eth3
set interfaces switch switch0 switch-port interface eth4
set interfaces loopback lo
commit;save
```

You can also do the above configuration in the GUI under the dashboard. After I did this, I simply continued following @Genghis1227 steps and it's been working for me so far.

**Comment by Genghis1227** [comment]
@joshuarlowry I think what @saivanap98 said is spot on.  I don't have the Edgerouter X to test this out unfortunately.

**Comment by gb2bg** [comment]
Can the switch address be from any IP range? 
@joshuarlowry are you getting IPv6 addresses with this setup? It's been past 14 days and I still don't get ipv6 addresses for my setup.

**Comment by gb2bg** [comment]
weird I added the one line to my setup 
``set interfaces ethernet eth0 vif 0 dhcpv6-pd pd 1 interface switch0 service slaac``
and restarted to see IPv6 addresses for the switch.

**Comment by joshuarlowry** [comment]
Ipv6 worked for me out if the box. I still haven't set up the rest of the switch ports.
